### ISSUE TITLE
REST APIの結果のJSONの型

### ISSUE THREAD

**Issue by AyaMorisawa** [MissKernel/Misskey-DesignNote#10]
``` ts
{
  result: T | void;
  errors: {id: string, message: string}[];
}
```

**Comment by syuilo** [comment]
エラーかどうかはステータスコードで分かるのでその型はエラー時のみで良いと思う

**Comment by syuilo** [comment]
エラーじゃないときは冗長になる

**Comment by AyaMorisawa** [comment]
REST APIはStreaming APIから呼ばれることを想定してるのでステータスコードを得られるとは限らない

**Comment by syuilo** [comment]
では、内部でAPI自体は結果、エラーを返すようにして、それを見て、Streamingではそのような型に当てはめ、RESTではエラー時のみそのようなエラー専用の型を使うというのはどうでしょう

**Comment by AyaMorisawa** [comment]
ということはREST APIの結果のJSONはこうなります？

``` ts
T | {id: string, message: string}[]
```

**Comment by syuilo** [comment]
idとmessageは何を表していますか？

**Comment by AyaMorisawa** [comment]
エラーを識別する文字列とエラーメッセージです

**Comment by syuilo** [comment]
なるほど

**Comment by syuilo** [comment]
そんな感じになりますね
