### ISSUE TITLE
Userコレクション

### ISSUE THREAD

**Issue by syuilo** [MissKernel/Misskey-DesignNote#12]
| 名前 | 型 | 備考 |
| --- | --- | --- |
| id | id |  |
| createdAt | date |  |
| name | string |  |
| screenName | string |  |
| screenNameLower | string | 検索時に利用 |
| comment | string |  |
| description | string |  |
| color | string |  |
| email | string |  |
| isEmailVerified | boolean |  |
| lang | string |  |
| location | string |  |
| hashedPassword | string |  |
| credit | number |  |
| pinnedStatusid | id | ピン留めするstatusのID |
| websiteUrl | string |  |
| iconid | id | アルバム内の画像のID |
| bannerid | id | アルバム内の画像のID |
| wallpapeidr | id | アルバム内の画像のID |
| birthday | date |  |
| isVerified | boolean |  |
| isPro | boolean |  |
| isPrivate | booblean |  |
| isDeleted | booblean |  |
| isSuspended | boolean |  |

**Comment by AyaMorisawa** [comment]
コレクションごとにIssue作ろう

**Comment by syuilo** [comment]
ok

**Comment by AyaMorisawa** [comment]
id型とは何ですか？

**Comment by AyaMorisawa** [comment]
`emailaddress` は `email` の方が良いのでは？

**Comment by syuilo** [comment]
+1

**Comment by syuilo** [comment]
idはstringか

**Comment by AyaMorisawa** [comment]
`iconImage`, `bannerImage`, `wallpaperImage`はそれぞれ`icon`, `banner`, `wallpaper`にしよう

**Comment by syuilo** [comment]
ok

**Comment by AyaMorisawa** [comment]
`screenName` を `screenNameToDisplay` にして `screenNameLower` を `screenName` にするのはどうでしょうか？
Lowerだと何のためにあるのかが分かりにくい気がします。

**Comment by syuilo** [comment]
**screen**NameTo**Display** で意味が被ってるような

**Comment by syuilo** [comment]
screenName に関しては今のままで良い気がする

**Comment by syuilo** [comment]
screenNameLowerを利用する場面は限られますのでそっちの方が簡潔そう

**Comment by AyaMorisawa** [comment]
なるほど

**Comment by AyaMorisawa** [comment]
`password` を `hashedPassword` にするのはどうでしょうか？

**Comment by syuilo** [comment]
+1

**Comment by AyaMorisawa** [comment]
`mobileHeaderDesignId` はブラウザ側で保存できないかな

**Comment by syuilo** [comment]
ブラウザ側で保存すると他の人から参照できなさそう

**Comment by syuilo** [comment]
そういうWebだけの情報はWebサーバー側でコレクション作ってもいいかも

**Comment by AyaMorisawa** [comment]
ああ他の人が参照するならサーバーで保存する必要があるな

**Comment by syuilo** [comment]
Disskeyの設定をMisskeyのDBに保存したりしないですしそうしてもいいかも

**Comment by syuilo** [comment]
そっちの方がすっきりするな

**Comment by AyaMorisawa** [comment]
Webだけの情報はWebサーバー側でコレクション作りましょう

**Comment by syuilo** [comment]
yeah

**Comment by syuilo** [comment]
mobileHeaderDesignId を削除した

**Comment by AyaMorisawa** [comment]
そうすると `mobileHeaderDesignId` はここから要らなくなるかな

**Comment by AyaMorisawa** [comment]
`point` は何でしょうか？

**Comment by syuilo** [comment]
あの名称が決まっていない仮想通貨のようなものですね

**Comment by syuilo** [comment]
何か良い英単語ありますかね

**Comment by AyaMorisawa** [comment]
仮想通貨に名称つけてそれを使うのが良さそう #17

**Comment by syuilo** [comment]
これもまた決まりそうにないのでStatusのように内部で何らかの名称を付けたい

**Comment by syuilo** [comment]
`credit`とか

**Comment by AyaMorisawa** [comment]
:+1: for `credit`

**Comment by AyaMorisawa** [comment]
bioはなくても大丈夫ですか？

**Comment by syuilo** [comment]
BIOを廃止するかどうか考えている

**Comment by syuilo** [comment]
名前だけ変えよう

**Comment by syuilo** [comment]
「自己紹介」に相当する良い語はあるだろうか

**Comment by syuilo** [comment]
`description`にしましょうかね

**Comment by AyaMorisawa** [comment]
:+1: for `description`

**Comment by syuilo** [comment]
Added `description` column

**Comment by syuilo** [comment]
ひとまず確定

**Comment by AyaMorisawa** [comment]
`isDeleted` はどうしましょう

**Comment by syuilo** [comment]
そうだった

**Comment by syuilo** [comment]
Add `isDeleted`

**Comment by syuilo** [comment]
非公開アカウントのための`isPrivate`を追加。

**Comment by syuilo** [comment]
凍結されているかどうかを表す`isSuspended`を追加。

**Comment by syuilo** [comment]
ユーザーカラーを表す`color`を追加。

**Comment by syuilo** [comment]
emailが確認されているかを表す`emailVerified`を追加。

**Comment by AyaMorisawa** [comment]
`isVerified` と合わせて `emailVerified` を `isEmailVerified` にするのはどうでしょうか？

**Comment by syuilo** [comment]
cool

**Comment by syuilo** [comment]
Updated
