### ISSUE TITLE
Statusコレクション

### ISSUE THREAD

**Issue by syuilo** [MissKernel/Misskey-DesignNote#13]
| 名前 | 型 | 備考 |
| --- | --- | --- |
| id | id |  |
| createdAt | date |  |
| userId | id |  |
| appId | id | 投稿に使用したアプリケーションID(公式はnull) |
| cursor | number | 投稿の新旧を指定した取得の際に用いる連番の値 |
| text | string |  |
| attachedFileIds | id[] | 添付されたコンテンツのIDの配列 |
| inReplyToStatusId | id |  |
| isPlain | boolean | trueだとmarkdownとして解釈しない |
| isModified | boolean |  |
| isDeleted | boolean |  |

**Comment by AyaMorisawa** [comment]
`isDeleted` を追加しよう

**Comment by syuilo** [comment]
Added

**Comment by syuilo** [comment]
`images`を`attacheds`に変更

**Comment by syuilo** [comment]
`inReplyToStatusId`を追加
