### ISSUE TITLE
AlbumFileコレクション

### ISSUE THREAD

**Issue by syuilo** [MissKernel/Misskey-DesignNote#15]
| 名前 | 型 | 備考 |
| --- | --- | --- |
| id | id |  |
| createdAt | date |  |
| name | string |  |
| userId | id |  |
| serverPath | string | 実際に格納されている配信サーバーのパス 例: a/b/c.jpg |
| folder | id | 格納されている[フォルダ](https://github.com/MissKernel/Misskey-DesignNote/issues/27)のID。ルートにある場合は`null` |
| tags | string[] |  |
| dataSize | number | 情報量としての大きさ |
| properties | any | 例えば画像なら画像の幅、高さ、exifなどの情報 |
| mimeType | string | MIME Type |
| hash | string | ハッシュ値 |
| isHidden | boolean |  |
| isPrivate | boolean |  |
| isDeleted | boolean |  |

**Comment by AyaMorisawa** [comment]
`type` は `format` の方が良いのでは？

**Comment by syuilo** [comment]
+1

**Comment by syuilo** [comment]
Renamed ty

**Comment by syuilo** [comment]
`size`だとデータの量的な意味なのか幅とか高さ的な意味なのか分かりにくいので、何か良い語はあるだろうか

**Comment by syuilo** [comment]
Renamed to `dataSize`

**Comment by syuilo** [comment]
ひとまず確定

**Comment by AyaMorisawa** [comment]
`name` はユニークなプロパティですか？

**Comment by syuilo** [comment]
`userId`と`name`で複合ユニークです

**Comment by syuilo** [comment]
フォルダ機能と関連がありそうでややこしいので`path`を`serverPath`に変更しました。

**Comment by syuilo** [comment]
`folder`プロパティを追加しました。

**Comment by AyaMorisawa** [comment]
`folder`はフォルダ名の配列にしてルートにある場合は空の配列にするのはどうでしょうか？階層を表すためです。

**Comment by syuilo** [comment]
Folder自体が親を表せるのはどうでしょうか？

**Comment by syuilo** [comment]
#27

**Comment by AyaMorisawa** [comment]
:+1:
