### ISSUE TITLE
Notificationコレクション

### ISSUE THREAD

**Issue by syuilo** [MissKernel/Misskey-DesignNote#18]
| 名前 | 型 | 備考 |
| --- | --- | --- |
| id | id |  |
| createdAt | date |  |
| userId | id |  |
| cursor | number | 新旧を指定した取得の際に用いる連番の値 |
| type | string |  |
| content | any |  |
| isRead | boolean | 既読かどうか |

**Comment by AyaMorisawa** [comment]
`content`には具体的に何が入ります？

**Comment by syuilo** [comment]
例えばふぁぼの通知だったら、

``` json
{
    "userId" : "55b871f0bc999dd43e416a4d",
    "statusId" : "55dfdf873551b6c931ba8ab9"
}
```

のような感じです

**Comment by AyaMorisawa** [comment]
なるほど

**Comment by syuilo** [comment]
APIのレスポンスとして返すときは、このIDは実体化されます

**Comment by AyaMorisawa** [comment]
実体化とは？

**Comment by syuilo** [comment]
`userId`をuserのオブジェクトにしたり

**Comment by AyaMorisawa** [comment]
通知の種類を一覧にしてまとめたい
