### ISSUE TITLE
Applicationコレクション

### ISSUE THREAD

**Issue by syuilo** [MissKernel/Misskey-DesignNote#20]
| 名前 | 型 | 備考 |
| --- | --- | --- |
| id | id |  |
| createdAt | date |  |
| userId | id |  |
| appKey | string |  |
| callbackUrl | string |  |
| description | string |  |
| iconid | id |  |
| permissions | string[] |  |
| isSuspended | boolean |  |
| isDeleted | boolean |  |

**Comment by AyaMorisawa** [comment]
`callbackUrl` について認証時に遷移するかどうかはクライアント側で決められるようにするのはどうでしょう

**Comment by syuilo** [comment]
Webアプリケーションの場合遷移しないと認証が完了しなくないですか？

**Comment by AyaMorisawa** [comment]
認証ページを開くときに遷移するかどうかをクライアント側からパラメータ送る

**Comment by syuilo** [comment]
遷移しないケースなんてありますかね

**Comment by AyaMorisawa** [comment]
Webアプリケーションでないケース

**Comment by syuilo** [comment]
WebアプリケーションでないケースはCallbackURLに何も記述しないのでそこで判断していますよね

**Comment by AyaMorisawa** [comment]
`callbackUrl` を廃止してクライアント側からパラメータ送ることによって判断するのはどうでしょうか？

**Comment by syuilo** [comment]
ふむ

**Comment by syuilo** [comment]
でもMisskey側でそのアプリケーションがWebアプリケーションか否かを判断できるようにしたい

**Comment by AyaMorisawa** [comment]
なるほど

**Comment by AyaMorisawa** [comment]
permissionsには具体的にどのような文字列が入ります？

**Comment by syuilo** [comment]
そうですね、`post-status`や`access-album`みたいな感じでしょうか

**Comment by AyaMorisawa** [comment]
アプリの権限名については別途Issueを作りましょう

**Comment by syuilo** [comment]
ok
