### ISSUE TITLE
ユーザーページのURLとその他のURLの区別

### ISSUE THREAD

**Issue by ghost** [MissKernel/Misskey-DesignNote#32]
現状のように[ユーザーページのURL](http://misskey.xyz/misskey)や[その他のURL](http://misskey.xyz/bbs)の形式が同じだと新しいページやユーザーを作る時などにURLの衝突が起きる可能性があるので、新MisskeyではユーザーページのURLをmisskey.xyz/users/misskeyなどのようにURLを区別するべきかと。

**Comment by syuilo** [comment]
今のままにします。
